# Corrigindo o TimeZone do host para America/SP
# Fontes
# https://docs.ansible.com/ansible/latest/modules/timezone_module.html
---

- hosts: all
  gather_facts: False
  remote_user: linux
  become: yes
  become_user: root
  become_method: sudo

  tasks:
   - name: Corrigindo TimeZone para SP
     timezone:
       name: America/Sao_Paulo


                      
