# Alterando ou adicionando a porta SSH
# Fontes
# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
# https://docs.ansible.com/ansible/latest/modules/systemd_module.html
---

- hosts: all
  gather_facts: True
  remote_user: linux
  become: yes
  become_user: root
  become_method: sudo

  tasks:
#    - name: Alterando a porta SSH
#      lineinfile:
#        path: /etc/ssh/sshd_config
#        regexp: '^Port 22'
#        line: Port 2222

    - name: Adicionando porta SSH para acesso externo
      lineinfile:
        path: /etc/ssh/sshd_config
        line: Port 1234

    - name: Reiniciando servico do SSH
      systemd:
        state: restarted
        daemon_reload: yes
        name: ssh
