# Validando se o host esta com o python instalado
---

- hosts: all
  gather_facts: False
  remote_user: linux
  become: yes
  become_user: root
  become_method: sudo

  tasks:
   - name: Install Python 2
     raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python)


                      
