# Instalando o docker-ce no Ubuntu
#Fontes
#https://is.gd/PqPU2m << Installing docker and docker-compose on remote server with Ansible
#https://is.gd/7E5XtW << Ansible - Add an apt-repository on Debian and Ubuntu
---
- hosts: all
  gather_facts: True
  remote_user: linux
  become: yes
  become_user: root
  become_method: sudo

  tasks:
   - name: Instalando pacotes necessario para o docker
     apt:
      name: "{{ items }}"
      state: latest
      update_cache: yes
     vars:
        items:
        - apt-transport-https 
        - ca-certificates 
        - curl  
        - software-properties-common
        - htop
        - iotop
        - iptraf-ng
        - vim

   - name: add docker apt-key
     apt_key: 
       url: https://download.docker.com/linux/ubuntu/gpg 
       state: present 

   - name: add docker apt repository
     apt_repository: 
       repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable' 
       state: present 
       filename: docker 
       update_cache: yes

   - name: Instalando o docker-ce
     apt:
      name: "{{ items }}"
      state: latest
      update_cache: yes
     vars:
       items:
       - docker-ce 
                      
