# Instalando chave SSH do root para o servidor
# Exemplo de execucao
# ansible-playbook 02-instala-keyssh-root.yml -i /tmp/hosts -k --ask-become-pass
#
# Fontes
# https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html
---
- hosts: all
  gather_facts: False
  remote_user: brqssh
  become: yes
  become_user: root
  become_method: sudo

  tasks:
   - name: Adicionando chave SSH para o root
     authorized_key: 
       user: root
       exclusive: False
       key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


                      
